### ISSUE TITLE
Rewrite Rules for trep gametype

### ISSUE THREAD

**Issue by q3shafe** [q3shafe/trepidation#122]
Rewrite Rules for trep gametype

The code for the rules is a mess, such as when different turret types, immobilizers become available, health of the power core, etc.   Lets make these defines so that we dont have so much repetitive code.

**Comment by squiciene** [comment]
i have never done this before.  which file controls the game type?  i need to look at it.
i have been giving this some thought. thinking of something like specialties being added.  & extra team colors like green & yellow.  a 4 team base would look sweet  .....hmmmmm.... rules for scoring in a 3 or 4 team ctf match?   ......HMMMMMMMM    this would give 3 & 4 team matches,  upto 3 players or bots per team.
