### ISSUE TITLE
Team spawnpoints on map Dread are all messed up

### ISSUE THREAD

**Issue by q3shafe** [q3shafe/trepidation#142]
Team spawnpoints on map Dread are all messed up

**Comment by q3shafe** [comment]
Is there anything that can be done with this... Set the game to ctf with like 12 bots and you'll see what I mean

**Comment by squiciene** [comment]
sure, im on it.

    On Tuesday, March 5, 2019, 1:13:52 AM EST, Shafe Shaffer <notifications@github.com> wrote:  
 
 
Is there anything that can be done with this... Set the game to ctf with like 12 bots and you'll see what I mean

**Comment by squiciene** [comment]
do you want me to fix the original, or just replace it with the newer version of it?

**Comment by q3shafe** [comment]
hmmn... i say just drop the original... not sure tho... i guess we should
fix the original as well if it's not a huge deal

**Comment by squiciene** [comment]
will do

**Comment by squiciene** [comment]
i think this issue is closed.
