### ISSUE TITLE
multiple copies of TREPIDATION.EXE?

### ISSUE THREAD

**Issue by squiciene** [q3shafe/trepidation#149]
im having a problem in development. i SEEM to have two different versions of the TREP executable.
one is the normal executable, the other only gets used when i have compiled a map in Radiant.

the settings on the two versions  differ wildly.   i really need an audio conference instead of a forum on this. 
there are a few weird things going on here. configurations differ between the two copies. i have no clue where the hell the other copy is located. Trep seems to want to send a lot of other files to unknown locations as well. the default bot i use in the regular EXE differs from the default bot i use when the game is loaded by Radiant.

i thought i had failed to fix the water problem in SKYPARK as it did not work when i went into TREP.  but later on after i had compiled a test map & then decided to check on sky park after radiant had opened TREP, & the water was working.

i went back to the normal executable & loaded the map, but the water wont work. ... but still works when TREP is loaded by radiant.

i really have no clue why this is happening or how, but if the executable that comes with the game can be made to behave as it does after radiant opens it, then i can get the voyager water to work in trep.

**Comment by q3shafe** [comment]
lets talk soon.  In the meantime, check C:\Users\[YOUR WINDOWS USERNAME\AppData\Roaming\trepidation

be sure there aren't any config files or pk3's that would be causing problems.  You can pretty much move anything there to your base folder aside from pakX-vms.pk3  kill that if it is in your appdata folder.

**Comment by q3shafe** [comment]
I assume this got worked out?  Feel free to re-open the issue if it hasn't.
