### ISSUE TITLE
things that need to be added

### ISSUE THREAD

**Issue by squiciene** [q3shafe/trepidation#150]
1- we really need an official SCREENSHOT button & re-allocation of the location & creation of the SCREENSHOTS folder, & perhaps a folder for DEMOS.

2- we really need a SPECTATOR button in the menu.  i have not used SPECTATOR yet (though i really need it as a developer), because i cant remember the command line.  using command lines in development is one thing, but we should not expect that out of players.

3 - need zoom on all long range weapons & needs to be assignable to any key, not on the weapon itself.
is there a zoom feature in SPECTATOR?  if not - there needs to be.

4 - need a USE OBJECT button that can be assigned to any key.  not to be confused with USE ITEM.

**Comment by q3shafe** [comment]
> 1- we really need an official SCREENSHOT button & re-allocation of the location & creation of the SCREENSHOTS folder, & perhaps a folder for DEMOS.

It's in there... I think by default it is bound to f11, but I would need to check this.  This should just be a matter of updating the default.cfg file with the correct bind if it isn't already there.  

The logic about how things get saved in the appData folder of that particular windows user is this (which I don't particularly agree with).  -- You share a computer with some siblings or other people, you download a weapons pack that changes all of your weapons, all users on that computer don't have to deal with it, just the user who downloaded it.  On the flipside, the same goes with maps, if you downloaded a map from a server, and someone else (another user on the computer) tries to play a server with the map, they would also have to download it, thus causing 2 copies sitting on the hard drive taking up space.  Again, this was an option on how stuff was stored in some very early build.  It's worth putting back in there.

> 2- we really need a SPECTATOR button in the menu. i have not used SPECTATOR yet (though i really need it as a developer), because i cant remember the command line. using command lines in development is one thing, but we should not expect that out of players.

Look in the in game menu under join match, spectator is in there.

> 3 - need zoom on all long range weapons & needs to be assignable to any key, not on the weapon itself. is there a zoom feature in SPECTATOR? if not - there needs to be.

There is not a zoom, zoom was never included in the original q3 codebase, we made a specific zoom for a single weapon, I don't see why this can't be adapted to also work in spectator.  

> 4 - need a USE OBJECT button that can be assigned to any key. not to be confused with USE ITEM.

It's on the to-do list for the code.  I may open some separate issues for some of these and assign them to myself as us programmers live off of issue lists. :)

**Comment by q3shafe** [comment]
Updated base config defaults to include f11 bound to /screenshot

**Comment by q3shafe** [comment]
It will be available in mondays snapshot.

**Comment by q3shafe** [comment]
On the zoom issue, I'd prefer to not have zoom available across the board, I think it makes sense for the rifle that actually has a scope, but I don't know about the rest.  Zoom in spec is def something that can be figured out.

**Comment by q3shafe** [comment]
I'm going to close this and put these out as separate issues.
