### ISSUE TITLE
skybox problem

### ISSUE THREAD

**Issue by squiciene** [q3shafe/trepidation#151]
hey Shafe, 
ive been reading up in the Q3A shader manual about skyboxes.  heres an excerpt.

•	Be aware that the skybox does not wrap around the entire world. The “floor” or bottom face of the skybox is not drawn by the game. If a player in the game can see that face, they will see the “hall of mirrors” effect.

it would open a lot of doors in design & development of maps for me if we could include the bottom skybox texture.  i made a couple skyboxes that looked really nice, but so far the shader does not control this issue from what i have tested.

im pretty sure this can be changed in the coding, will you look into fixing this please?

**Comment by q3shafe** [comment]
Is this something that is supported in EF?  Maybe I can get an idea where this code is by looking in the EF code.

**Comment by squiciene** [comment]
yes,  the skybox bottom texture is supported in EF.  

thanks Shafe
chris
 

    On Thursday, November 30, 2017 10:38 PM, Shafe Shaffer <notifications@github.com> wrote:
 

 Is this something that is supported in EF? Maybe I can get an idea where this code is by looking in the EF code.—
