### ISSUE TITLE
Console error regarding liquids.shader file

### ISSUE THREAD

**Issue by q3shafe** [q3shafe/trepidation#157]
Console error regarding liquids.shader file
Check it out.

**Comment by squiciene** [comment]
um... need some info with that bro.  whats the error?   are we talking about TREP liquids.shader file? ... or STVEF liquids.shader file compatibility?     is there something here in the issues forum that i can click on to "check it out" ?

**Comment by q3shafe** [comment]
You know.. I think this was happening on a failed test build of the game I haven't seen it again since rebuilding.
