### ISSUE TITLE
New defaults are incorrect

### ISSUE THREAD

**Issue by angrynerd** [q3shafe/trepidation#162]
the new default of r_ext_texture_filter_anisotropic "4" is incorrect as this command has only 0 or 1 and states whether or not anisotropic filtering is used. the command r_ext_max_anistropy should be set to 4 and r_ext_texture_filter_anisotropic should be set to 1 to achieve the desired effect. [this](http://openarena.wikia.com/wiki/Manual/Graphic) is the information i am basing this claim off of.

**Comment by q3shafe** [comment]
Corrected, binaries have not been rebuilt though.
