### ISSUE TITLE
doors

### ISSUE THREAD

**Issue by squiciene** [q3shafe/trepidation#163]
the FUNC_DOOR entity leaks light through, as if the door were transparent.  it looks really awful behind the stargate in Dystopia 2.  i have done all i know to do to resolve this,  im guessing the problem is in the coding.

**Comment by q3shafe** [comment]
does this seem relevant?

https://forums.splashdamage.com/t/func-door-model2-key-only-working-on-mapping-q3-install/110520

**Comment by squiciene** [comment]
this is still an issue, but im starting to like it.  it can offer a clue that a secret door is present.  im also learning new ways to place lights behind doors, so that the light wont bleed out under the door (trepxsus2).    so yes, it is still occurring, but i think i can manage to work around it.  for now, i  consider this issue closed.
