### ISSUE TITLE
entities

### ISSUE THREAD

**Issue by squiciene** [q3shafe/trepidation#164]
ive been having this problem since  i started map building.  the engine does not like too many entities in complex maps.  im not sure why, but i suspect its because when these old games were released, PCs were a LOT slower than they are today, so i think the game developers limited how many entities can be placed in a map.....but im not certain of that.  it could simply be a limitation of the engine.

right now Dystopia 2 is turning out to be the best map yet for TREPIDATION, but i may have to drastically undo a lot of what i have already done, due to this limitation of entities.  as it is, when i compile the map & then bot support, & then try to run the map, i get the error that the "default model" failed to load.  i have been dealing with this issue since  i started map building, & the only solutions so far have been one of the following;  reduce the size of the map - reduce the complexity of the structures in the map - reduce the amount of entities - reduce the amount of lighting - reduce all the above - or reduce the "_LIGHTMAPSCALE" of the map.... that last option can really make a map look nasty sometimes.

entities include;  lights - weapons & armor - ammo & or health pick-ups - doors - platforms - rotators - pendulums - function groups - & holdable items.

generally i have to under-equip a map to get bot support when this happens & it happens a lot.
it would benefit the game greatly if we could place more entities within a map that has bot support.

now, if you dont want bot support in a map, then this is not a problem at all. i can load a map to the roof with entities & have no problems.....  but thats a very unplayable game.

any chance you can increase the number of entities that can be placed in a map?

**Comment by q3shafe** [comment]
Hey,

I'm pretty unavailable with until after the new year, y'know life crap, holidays etc.

We can def change up the number of entities, as that certainly is a reflection of older hardware whereas those limits or irrelevant now.

I've ran into the default model thing a few times.  I can usually get around this by going in to the player settings and resetting the player model.  (this is on my list of things to address).

I'll get a build with the new upper limits here in the next few days.  

I haven't responded yet, but I completely agree, dystopia looks freaking amazing.  I was blown away walking around on the copy you sent.

Cheers,
Shafe

**Comment by q3shafe** [comment]
I think I got this.. although there is some confusing bit in the code it is in the latest snapshot ( https://planettrepidation.tk/downloads/?lid=30 ).  At bare minimum you'll need the .exe and the new pak0-vms.pk3 out of there to test.  

Like I said, there is a bit of bizarre code in there for this. Let me know if it works.
