### ISSUE TITLE
entity shadows

### ISSUE THREAD

**Issue by squiciene** [q3shafe/trepidation#166]
the shadows on entities are penetrating walls, creating dual shadows & creating ghost shadows in the air.
im not sure if you can do anything about it until we have a model maker on board the project.
im not sure if i have uploaded the pics below in the right way, so i hope this works.  the following pics show the effect.  the shadows you can see in the air appear & disappear according to where your point of view is located.   if these pics cant be viewed here, let me know & i will email the pics. 
![ent_shadows_01](https://user-images.githubusercontent.com/33503125/34580867-726c6fac-f15c-11e7-8d05-54c293bf3ad9.jpg)
![ent_shadows_03](https://user-images.githubusercontent.com/33503125/34580882-7b17cd18-f15c-11e7-803a-7be76fdcd744.jpg)
![ent_shadows_06](https://user-images.githubusercontent.com/33503125/34580894-84ed8be8-f15c-11e7-9f1b-409e83b5ab11.jpg)
![ent_shadows_07](https://user-images.githubusercontent.com/33503125/34580898-87c69904-f15c-11e7-9317-76392aaeaa08.jpg)

**Comment by squiciene** [comment]
i forgot to mark the last pic.  if you look in the air where you also saw the mega health shadow, you will faintly see the invisibility shadow floating there.

**Comment by q3shafe** [comment]
I had this issue as well.  It was one of the renderer settings.  I don't recall of the top of my head which one.  I'll look it up when I'm not working.   Maybe cg_shadows ??  What do you have that set at?

**Comment by squiciene** [comment]
as far as i know, i haven't set cg_shadows to anything at all. i think its either in the coding or more likely has something to do with the shader for the model.. 

    On Thursday, January 4, 2018 3:19 PM, Shafe Shaffer <notifications@github.com> wrote:
 

 I had this issue as well. It was one of the renderer settings. I don't recall of the top of my head which one. I'll look it up when I'm not working. Maybe cg_shadows ?? What do you have that set at?—

**Comment by angrynerd** [comment]
Afaik this issue is cause by how the light sources interact with the accurate shadows of the entities. Setting shadows to 1 hoever will essentially remove all but the most basic shadows.

**Comment by squiciene** [comment]
ok i will give it a try.

    On Monday, October 15, 2018, 7:34:51 PM EDT, Skylar Shaffer <notifications@github.com> wrote:  
 
 
Afaik this issue is cause by how the light sources interact with the accurate shadows of the entities. Setting shadows to 1 hoever will essentially remove all but the most basic shadows.

**Comment by squiciene** [comment]
cg_shadows does fix the problem for me.   but i think that unless new players know how to activate this, they are gonna see shadows everywhere & not know they can get rid of them.

**Comment by angrynerd** [comment]
It was added by default because they look better as shadows. However it may
be worth making it default to one to fix all of the dirrection issues it
causes.
