### ISSUE TITLE
Bot difficulty

### ISSUE THREAD

**Issue by angrynerd** [q3shafe/trepidation#170]
After playing quake 3 and trep side by side for a few weeks i have noticed that our bots feel easier. While the stats on paper are more or less the same bar a few modifications they weak in gameplay. For example our skill 4 bots are probably closer to quake 3 skill 2 bots. I feel this issue is a result of the dissision to prevent or really limit the bots from using the gaus rifle. This needs to be reworked in a way to which they will use it more but not all the time. If you have other ideas as to why they feel under powered please suggest them.

**Comment by q3shafe** [comment]
The bot weapon preferences are in the botfiles, do you want to do some tweaks and see how it works?

**Comment by angrynerd** [comment]
Ya i mean give it a shot and if i notice anything after i will adjust as
nessesary.

**Comment by q3shafe** [comment]
Not sure why that would happen.... operator error ? :)

**Comment by q3shafe** [comment]
This is getting addressed in another issue.  closing.
