### ISSUE TITLE
Map Download Server

### ISSUE THREAD

**Issue by angrynerd** [q3shafe/trepidation#171]
Hello, I was trying to setup an apache2 web server to service maps to incoming clients of my local snapshot server. I setup all of the directories and commands as it states to in several wikis. Unfortunately when i attempted to download a map from the web server in game it spat out an error of miss matched files. this is impossible because the maps on the server were copied directly from the game server. I can't seem to figure out what the error is.

I have taken several steps into debugging this issue. first i recopied the maps to ensure the correct versions. i checked the clients appdata and that was clear of maps. i tried running with the default dl server with the same error. i tried reinstalling but i figured that wouldn't work as the error was occurring for my friend as well. As a last stitch effort i ran the latest dev build (0.0.20 as of the date of post) with the same maps, directories, and configs and to my surprise the dl servers worked fine with no errors. This leads me to believe that it is an error with the latest snapshot and not an operator error.

My setup is a linux mint 19 laptop running the latest apache2 server in the default repository as of the date posted. The client is a Windows 7 laptop. Both of the machines are both on the same physical network and connected by a Logmein hamachi network. The map i was testing with was chronic . The snapshot i was working with was the latest as of the date posted. There is no Firewall on the router and all access is allowed on the client and server which can be shown because the dev server still worked. The format of the url used is http://ip/mods/trep_extra where in the listed directory is the base folder with the maps. My client autoexec and server cfg as well as a condump will be posted bellow. 

Any help with this issue will be much appreciated and i hope to see this fixed before the next dev build. 

[debug.zip](https://github.com/q3shafe/trepidation/files/2407296/debug.zip)

**Comment by q3shafe** [comment]
This was resolved.
