### ISSUE TITLE
Fps issues

### ISSUE THREAD

**Issue by angrynerd** [q3shafe/trepidation#173]
I have found the culprit of my low fps and its stupid. The culprit was r_finish 1 which makes the gpu finish every frame. This sounds normal but it was halving or worse my frame rate. Unfortunetly this cvar is enabled by default. I feel this should be changed. Setting this to 0 as i have done can cause wierd input lag on certain gfx cards so i recomend a section in the wiki on it.

**Comment by q3shafe** [comment]
I'll add this to the wiki here shortly.
