### ISSUE TITLE
map bottom texture

### ISSUE THREAD

**Issue by angrynerd** [q3shafe/trepidation#174]
In all new maps an many previous maps the bottom bounding box of the map has been shown to look like this: 
![shot0003](https://user-images.githubusercontent.com/24483958/46911834-2ffb1300-cf35-11e8-9659-76944a878ed6.jpg)
I'm proposing that the skybox texture be mirrored over the bottom bounding box if no texture for it is present to prevent issues like this.

**Comment by q3shafe** [comment]
I think this is a limitation of the game itself.. I see this on countless maps.. I'm going to close this for now.
