### ISSUE TITLE
file override

### ISSUE THREAD

**Issue by squiciene** [q3shafe/trepidation#178]
im having a issue with putting files in the base folder to override files in the PAK files.   in the VOYAGER game, if i put a new file in the base folder to replace an existing PAK file, the engine lets the file in the base folders override the file in the PAK file.  but in TREP whatever is in the PAK file will override whats new that i put in the base folders to replace old versions.  this makes replacing textures that are already in the PAK file impossible to see until the new rebuild has included them.

can this be fixed?

**Comment by q3shafe** [comment]
If you zip up the files rename them to *.pk3 and name them with some zzzzz's in front of it, like zzzznewstuff.pk3 it should override any duplicates already in there.  Let me know if this works for you.
