### ISSUE TITLE
flag script

### ISSUE THREAD

**Issue by squiciene** [q3shafe/trepidation#179]
i just had a look at the newest dev snapshot.   the only thing i saw not working was one of the flag scripts.
some of the metallics used for a few flags are supposed to make the metallics wave like a banner in the wind.
it looks really cool on a few of the flags.

use this attached shader file to replace the old one & fix the issue.  if it does not work, let me know plz.

[squi_fx.zip](https://github.com/q3shafe/trepidation/files/2575625/squi_fx.zip)

cheers

**Comment by q3shafe** [comment]
I have this committed, haven't had a chance to look at it, it should be in the next snapshot next week.  I'll comment or close this out if when I can have a look.
