### ISSUE TITLE
New Maps/Remakes What to Keep, What to Replace

### ISSUE THREAD

**Issue by q3shafe** [q3shafe/trepidation#181]
We have some major modifications, fixes and overhauls to some of the existing maps.

Some of these maps such as dystopia and pyramide (to name a few) had some major issues which have been resolved in the overhauls.

some of these overhauls have layout changes to the map itself.  So the question I have, which maps do we replace for the next release, and which maps do we have a version 1 and version 2 of?

Here are the maps in question:

ctf_trepxus_2 
ctf_pyramid2
ctf_aversion_2
ctf_battlefield_2
dystopia_2
oarpg3dm2_s 
station145
Trep_War_Ring_2

I need to go through and have another look at all of them, but the ones I def want to completely replace with the overhauled versions are.

ctf_pyramide2 - major bot issues on the 0.0.20 version, the new version is so much better
dystopia - Has some issues of getting stuck in the walls, which is super annoying, not to mention the new one is amazing.

I'll likely add to my list of opinions soon, thoughts?

**Comment by squiciene** [comment]
i currently only have a request to save 3 original maps.  Trepxus/ station 144/ & junction.  Gigon did a very good job on the design of those maps & i would not want to rob him of the validation he deserves. i think that i did improve on what he began, but without that beginning, i would not have been able to produce the improved versions.

**Comment by q3shafe** [comment]
I think I'll add war ring to the list, that is also one of gigons

**Comment by q3shafe** [comment]
Y'know.. I'm kinda leaning on replacing the original trepxus and junction with your revised versions.  Gigon hasn't been mapping for awhile now, would it be possible to spit credit on the loading screen and/or a weird plaque in the map with the credits?

**Comment by squiciene** [comment]
that can be done.

    On Wednesday, March 6, 2019, 3:14:31 AM EST, Shafe Shaffer <notifications@github.com> wrote:  
 
 
Y'know.. I'm kinda leaning on replacing the original trepxus and junction with your revised versions. Gigon hasn't been mapping for awhile now, would it be possible to spit credit on the loading screen and/or a weird plaque in the map with the credits?

**Comment by q3shafe** [comment]
I'll ace the old ones once you get the new ones all in place... I'll make a separate download as a map-pack with all the old versions for anyone who wants to play on the old versions.

**Comment by q3shafe** [comment]
===========================
** dystopia has been replaced with dystopia_2 and moved to ccdata - original moved into og-mappack

** ctf_battlefield has been replaced with ctf_battlefiled2 and moved to ccdata - original moved into og-mappack

===============================

**Comment by q3shafe** [comment]
Trep_War_Ring is replaced by Trep_War_Ring_2 now...

The original has moved into the of-mappack folder

**Comment by q3shafe** [comment]
- ctf_trepxus has been replaced by ctf_trepxus_2 -- original lives in the og-mappack folder now

**Comment by q3shafe** [comment]
-ctf_aversion has been replaced with ctf_aversion_2 original now resides in the og mappack
 
- ctf_junction is being replaced with ctf_junction_2, original is in the og mappack

**Comment by q3shafe** [comment]
Just a side note @angrynerd we should be putting all new files into pak1-ccdata.pk3

**Comment by angrynerd** [comment]
Ok good to know.
