### ISSUE TITLE
Linux only issues

### ISSUE THREAD

**Issue by angrynerd** [q3shafe/trepidation#183]
In atleast the latest snapshot and possibly latest release screenshots dont function correctly in Linux. 
they instead show something along these lines.
![image](https://user-images.githubusercontent.com/24483958/48667883-bbc10b80-eaae-11e8-9737-cb39a8f385fd.png)
The scoreboard also doesnt properly function for me, looking more like the one that you can sortof make out above. with out any entries.
lastly the pdg lock text doesnt show up on linux after you have shot the particle displacement grenade.
For reference i am using the latest linux mint 64 bit for my tests.

**Comment by q3shafe** [comment]
are you using the 64 bit client binary?

**Comment by angrynerd** [comment]
The issues were happening on both 64 and 32 binaries.

**Comment by q3shafe** [comment]
can you retest this with the latest binaries dated 3-3-2019 (in the snapshot)

**Comment by q3shafe** [comment]
Also was this in a vm?

**Comment by angrynerd** [comment]
I havent got a chance to retest yet but no this wasnt a vm this was a
native install of linux mint 19.1.

**Comment by angrynerd** [comment]
Ok i have tested this on the latest snapshot and all three requested fixes are functioning.
