### ISSUE TITLE
Dev Snapshots

### ISSUE THREAD

**Issue by squiciene** [q3shafe/trepidation#184]
Developer Snapshot downloads are great for anyone who wishes to see what we have so far. but i just want my team to know - with all the experimental stuff i have on my PC for the development of TREP, when i download the dev snapshot & install it - all my experimental developments are still present & working. i dont get to see the flaws you guys see because i have ALL final materials.

if i send you a map & you see textures missing or effects not working, i NEED to see pics of it. the Dev Snapshot wont help me in this aspect.    

please understand -  i was not trained professionally, & my organization skills are not that great.  if i go moving stuff around so that i can see what you guys see in the dev snapshot,  im gonna get really lost & make a big screw up really fast.   

i have made changes to CFG files & other files outside of GTKRadiant to make my development issues disappear.  i dont fully understand all that i have done to make this possible, but it does seem to work for me right now.

if you see something not working right, please send me pics to my email.  this will help me to diagnose the problem MUCH faster.

Squiciene@yahoo.com

thanks
Chris

**Comment by squiciene** [comment]
lol  i forgot to mention the graphics setting i changed to get some of the scripts working.

under SYSTEM/GRAPHICS
set LIGHTING to LIGHTMAP  (do we really need VERTEX lighting option?)
set GEOMETRIC DETAIL to HIGH
set TEXTURE DETAIL to maximum

**Comment by q3shafe** [comment]
I'll have a look at the defaults there.   

As far as PK3s, pk3 files are just zip files renamed to pk3.   So once you have your folder structure setup, just zip it and rename it from .zip to .pk3 and you should be all set.

**Comment by squiciene** [comment]
i have re-installed Trepidation & the Trep Snapshot.   i am happy to say that everything seems to be working properly in the new maps.  one texture was missing though, & i have included  the fix with this comment.   this is for the wall inside the rotating in the center of the map.      just install to the appropriate folders.
[textures.zip](https://github.com/q3shafe/trepidation/files/2887181/textures.zip)
