### ISSUE TITLE
the file "msvcr100.dll"

### ISSUE THREAD

**Issue by squiciene** [q3shafe/trepidation#185]
the file "msvcr100.dll" is missing from the latest copy of "trep0020_setup.exe"     Trep will not run without it.  the same file is also not in the "trep_snapshot" file either.  the most up to date version of this file that i have is "msvcr100.dll    9/24/2017   9:50PM."

**Comment by q3shafe** [comment]
Hmmm that is the microsoft C redistributable..  msvcr100d is included, it shouldn't need an older one.  I'll have to look into that.  What version of windows are you running under?

**Comment by q3shafe** [comment]
this isn't in the snapshot, it is part of visual c++ sp1... ( here https://www.microsoft.com/en-us/download/details.aspx?id=26999&irgwc=1&OCID=AID681541_aff_7593_312327&tduid=(ir__3ti9pihtigkfrlmw0c1gdjgco32xhd0pwmpgf3xv00)(7593)(312327)()(06-3589464-11-0000000)&irclickid=_3ti9pihtigkfrlmw0c1gdjgco32xhd0pwmpgf3xv00 )

The snapshots now have the file, there was a bug in the build script.

**Comment by squiciene** [comment]
thanks Shafe!    btw - i use Win 7.

    On Wednesday, February 20, 2019, 9:08:23 PM EST, Shafe Shaffer <notifications@github.com> wrote:  
 
 
Closed #185.
