### ISSUE TITLE
trep0020_setup.exe & trep_snapshot

### ISSUE THREAD

**Issue by squiciene** [q3shafe/trepidation#187]
this is just an issue from my perspective, but....  why have the two files ( trep0020_setup.exe & trep_snapshot ) not yet been merged?

i ask because i have older relatives that would like to see my work, but asking them to replace files & enter commands in the drop down menu is a bit much for them.

when will the two files be merged?

**Comment by q3shafe** [comment]
I'd be down with putting out a trep0025_setup.exe -  A lot has been done since the 0020 release.  

I'll get to work on that.

**Comment by squiciene** [comment]
AWESOME!   dont do it too quickly.  in the next day or two i will be sending you the  new map ctf_junction 2
