### ISSUE TITLE
mp3 support

### ISSUE THREAD

**Issue by squiciene** [q3shafe/trepidation#188]
i seem to be having trouble with mp3s'.   what freq should i be using?  when the new trep 0025 comes out, can we integrate the "trepidation-mp3support.exe" into the "trepidation.exe" ?

**Comment by q3shafe** [comment]
it's super buggy and crashy... does it work well for you?

**Comment by squiciene** [comment]
i have had no issues with using it, except that i cant get an mp3 to play.    i have not used it for bot testing or game play.

    On Thursday, February 21, 2019, 10:46:09 PM EST, Shafe Shaffer <notifications@github.com> wrote:  
 
 it's super buggy and crashy... does it work well for you?

**Comment by q3shafe** [comment]
Originally the mp3 support was written in specifically for elite force but due to the licensing of mp3 they decided to not include it in the ioq3 engine.  I wouldn't mind having it back.

**Comment by angrynerd** [comment]
Im not sure it really matters as you can convert between formats using
audacity very easily.
