### ISSUE TITLE
New Opening Video

### ISSUE THREAD

**Issue by q3shafe** [q3shafe/trepidation#196]
The new version should really have a new opening video.. Have to remember how to make those roq files now... :)

Also I'll put together a promo video as referenced in another issue

**Comment by squiciene** [comment]
good to hear. plz remember to send me a link to the promo video when its posted.

**Comment by qubodup** [comment]
for future reference: https://www.moddb.com/games/quake-iii-arena/tutorials/how-to-create-a-roq-video-file1

**Comment by q3shafe** [comment]
done
