### ISSUE TITLE
Consolidate arena files into arenas.txt

### ISSUE THREAD

**Issue by q3shafe** [q3shafe/trepidation#198]
Consolidate arena files into arenas.txt

**Comment by squiciene** [comment]
im not sure i understand.  an .ARENA file is just a .TXT file.  are you saying you just want them as .TXT files?

**Comment by q3shafe** [comment]
Typically when you make a single stand alone map you put the
mapname.arena file in there that has the basic info.... For the
finished game (as a whole) they can all be put in one file called
arenas.txt which gets read first.

I'm not certain but I seem to remember seeing some .arena files
floating around in the pk3s..
