### ISSUE TITLE
map Dread

### ISSUE THREAD

**Issue by squiciene** [q3shafe/trepidation#199]
i have looked at this map & i can see why there are issues with team spawn points.  however, the map is SO boring, i couldnt help myself & started remodeling.  the few changes i have made so far have led me to decide that the original should just be scrapped when im done with this one.  

take a look at these pics & decide for yourself.  this is NOWHERE near finnished.  i have a few nice ideas in store for this map. 

![shot0000](https://user-images.githubusercontent.com/33503125/53929522-ffd71c80-405b-11e9-8e92-c6a6fb63379b.jpg)
![shot0001](https://user-images.githubusercontent.com/33503125/53929524-02397680-405c-11e9-80c0-42a1f737fce2.jpg)
![shot0002](https://user-images.githubusercontent.com/33503125/53929531-05346700-405c-11e9-98dc-8561acbdd329.jpg)
![shot0003](https://user-images.githubusercontent.com/33503125/53929537-0796c100-405c-11e9-8f25-cd559be82600.jpg)
![shot0004](https://user-images.githubusercontent.com/33503125/53929541-09608480-405c-11e9-800b-0f318322c5ae.jpg)

**Comment by squiciene** [comment]
hey guys, look, im ALWAYS open to ideas.  if you think of something you think should be added, please let me know.  im glad you like what i have been doing, but if there is something you would like to see, or see changed... just let me know.

**Comment by angrynerd** [comment]
Personally Dread is one of my favorite maps in terms of gameplay. im with you on the idea that the map was visually boring. any change is welcome but now that there is such a "high tech base" it makes the walls and floor of this map look a little dated. if this could be adressed that would be nice.

**Comment by angrynerd** [comment]
Underground and wall entrances may also be a decent idea.

**Comment by squiciene** [comment]
hmm..... i had not thought about tech in this map yet.  good call!   were you thinking something elaborate for an underground, or simple?   i was thinking about making a basement pool in the forts that connects to the front mote.   i think i will need to see how far a bot can swim before drowning. :)

here are a few more pics of the progress on Dread.

![shot0000](https://user-images.githubusercontent.com/33503125/54044790-d7573b80-419d-11e9-8e31-7172d98ef137.jpg)
![shot0001](https://user-images.githubusercontent.com/33503125/54044791-d7efd200-419d-11e9-9991-268aaad6af41.jpg)
![shot0002](https://user-images.githubusercontent.com/33503125/54044793-d7efd200-419d-11e9-989c-b0cf9babf6d2.jpg)
![shot0003](https://user-images.githubusercontent.com/33503125/54044794-d7efd200-419d-11e9-935d-0581a1758808.jpg)
![shot0004](https://user-images.githubusercontent.com/33503125/54044795-d7efd200-419d-11e9-8f25-852f3d66b3e9.jpg)

as you can see, i have moved the forts further apart leaving a nice open lawn to put a few obstacles & plants on.  mainly i am just reworking the forts for now.  

the insides will have to be expanded a bit to house a reasonable basement pool or well.  i would like this place to have a nice dungeon feel inside. also i want to start making more triggerable traps & shooters.

i may change the lighting here, unless you guys like the bright sun. i think a more satiny lighting would look better.  & just a bit less overall brightness.

i have big plans for the outside border wall.   well, not too big,  but i think it will make this map look a lot sweeter. im gonna go with a rusted metal wall. kind of hard to describe.  ill post pics when its in place.

what did you mean by "wall entrances"?   did you mean passages inside the hull walls, like on pyramid 2? or other entrances to the forts? or both?

**Comment by angrynerd** [comment]
by wall entrances i kinda ment something along the lines of what was done on war ring 2 with the extra parts inside the walls were there generally werent any before. im currious to see how this map comes out. good luck!

**Comment by angrynerd** [comment]
Side note new lighting for this map could definetly be a good idea as long as it doesnt break the original in the event there is a map pack that is made containing the older maps.

**Comment by q3shafe** [comment]
This is looking awesome

**Comment by squiciene** [comment]
the  new walls are mostly up.  i will make an ajustment later on to the outer wall, but this should give  you a good idea of what im cookin here.
![dread2_01](https://user-images.githubusercontent.com/33503125/54077911-6000d500-428d-11e9-982c-e92b394d1848.jpg)

![dread2_03](https://user-images.githubusercontent.com/33503125/54077916-7d35a380-428d-11e9-85f2-960b3e075b6a.jpg)
later im going to add a tower or two in the wall.    on the next pic, which do you guys like; the red interior lights, or the yellow ones?
![dread2_02](https://user-images.githubusercontent.com/33503125/54077938-ecab9300-428d-11e9-9db3-4aad56e2f9bc.jpg)
![dread2_04](https://user-images.githubusercontent.com/33503125/54077941-f59c6480-428d-11e9-950b-ddb3be0fbe45.jpg)
![dread2_05](https://user-images.githubusercontent.com/33503125/54077944-fb924580-428d-11e9-8629-14583fc49e7c.jpg)

**Comment by angrynerd** [comment]
Man that looks gorgeous keep olup the good work!

**Comment by squiciene** [comment]
thanks,  heres the last pic update for this map.  its getting close to finished.  i have a few more things to add & then get bot support.
![dread2_101](https://user-images.githubusercontent.com/33503125/54156792-5a39f980-441d-11e9-9dcc-76971f401ac4.jpg)
![dread2_102](https://user-images.githubusercontent.com/33503125/54156798-5efead80-441d-11e9-8eb5-a14e58cc5b6a.jpg)
![dread2_103](https://user-images.githubusercontent.com/33503125/54156803-61f99e00-441d-11e9-8244-961827f4ae64.jpg)
![dread2_104](https://user-images.githubusercontent.com/33503125/54156813-658d2500-441d-11e9-9a5f-152b93fc870a.jpg)
![dread2_105](https://user-images.githubusercontent.com/33503125/54156827-6aea6f80-441d-11e9-815a-a68af92beb84.jpg)
![dread2_106](https://user-images.githubusercontent.com/33503125/54156839-6f168d00-441d-11e9-956a-1846fee4d3f5.jpg)
![dread2_107](https://user-images.githubusercontent.com/33503125/54156840-6faf2380-441d-11e9-82f4-b5303bddd7f5.jpg)
![dread2_108](https://user-images.githubusercontent.com/33503125/54156842-7047ba00-441d-11e9-973b-d32b81676e0e.jpg)
![dread2_109](https://user-images.githubusercontent.com/33503125/54156844-7047ba00-441d-11e9-9b4d-48741eb2a6de.jpg)
![dread2_110](https://user-images.githubusercontent.com/33503125/54156845-70e05080-441d-11e9-94dd-8be1c99eb8e0.jpg)
![dread2_111](https://user-images.githubusercontent.com/33503125/54156846-70e05080-441d-11e9-8347-bf9e2e6bf10f.jpg)

this map is gonna rock!

**Comment by q3shafe** [comment]
damn, you work quick!

**Comment by squiciene** [comment]
ok guys - here it is     DREAD 2         Red Dread 2?  lmao
[base.zip](https://github.com/q3shafe/trepidation/files/2974481/base.zip)
all file within the zip file, are in their proper folders.

**Comment by squiciene** [comment]
heres the original one with a small texture redo.
also included are a few textures im not sure if you already have or not.
[dread.zip](https://github.com/q3shafe/trepidation/files/2974501/dread.zip)

**Comment by angrynerd** [comment]
i tested the newer map and it looks great im going to wait to commit though, im going to test the original now.

**Comment by angrynerd** [comment]
ok the modified original looks pretty good. im not sure about the white on blue base but the game play is great.

**Comment by squiciene** [comment]
awesome.   i can restore the textures on the original i you wish.  wont take but a few minutes.

**Comment by angrynerd** [comment]
Um idk we will see what @q3shafe thinks about this...

**Comment by q3shafe** [comment]
I'm indifferent on the retextures.. I like it both ways.  The new version looks damn amazing!

**Comment by angrynerd** [comment]
I wasnt going to close it before it was commited...
