### ISSUE TITLE
r_vertexLight

### ISSUE THREAD

**Issue by angrynerd** [q3shafe/trepidation#200]
This command controls which type of lighting is used for the game. for a long time it was defaulted to a value of one being vertex lighting. This breaks the textures on alot of new maps. most notably alot of trep war ring 2 is broken with it as well as all of the newer jump pads that are team colored. This may or may not have already been updated in the defaults but first needs to be updated in shafes config, and second should be added to the wiki. The fix for this is to set it to 0 being lightmap style which fixes the texture errors and looks a lot cooler and more moody. ONe example to be quickly seen is in #190 in the first screenshots jump pad.

**Comment by q3shafe** [comment]
This was already changed as a default...

**Comment by angrynerd** [comment]
But did you change it in your config as mentioned because you seem to be
having certain issues because of it.
