### ISSUE TITLE
sounds

### ISSUE THREAD

**Issue by squiciene** [q3shafe/trepidation#201]
i have experimented with 3 different sound formats without success.  the best result i could achieve was getting the speaker to play a static sound instead of the sound that should have played.  the dropdown window showed an error in red that said it could not load the file, & an error in yellow that said it could not find the file.

i tried this with .mpg format, .ogg format  & .wav format ,  all at 22k Hz.
i checked Gigons recording for the welcome to Junction.  it is a .wav @ 8k Hz  32 bitrate float
i havent yet experimented with bit rates yet.  i still have more testing to do.

**Comment by angrynerd** [comment]
One suggestion i can give you is to check and see how many chanels it is or
how big the file is. Im unsure what limits are currently imposed.

**Comment by angrynerd** [comment]
personally i would think that 22khz would work as it is one of the available audio settings in game but maybe it upscales it with some cpu processing?

**Comment by q3shafe** [comment]
wav and ogg are supported, but I'll have to digout the specs for those.

**Comment by q3shafe** [comment]
I've always went with .ogg (but I do remember the specs are very specific)   ogg compresses a lot smaller than an uncompressed wav file.

**Comment by q3shafe** [comment]
ogg should be mono @ 44kHz
Wav files should be uncompressed monon
