### ISSUE TITLE
bots stuck at elevator station 145

### ISSUE THREAD

**Issue by angrynerd** [q3shafe/trepidation#203]
When playing with bots on this map the bots will get stuck by the elevators and just walk back and forth untill a player makes them move. i think this may have also been an issue on the original but i cannot remember. if this can be fixed great but if not its not a big deal right now. also this was tested in dm other modes may draw the bot somewhere else. 
![shot0031](https://user-images.githubusercontent.com/24483958/54074720-ec969d80-4263-11e9-8fd5-ed65a85a5b50.jpg)

**Comment by squiciene** [comment]
that will be a tricky issue to get around.  ill see what i can do.

**Comment by angrynerd** [comment]
As i said if possible, if not dont worry about it.

**Comment by angrynerd** [comment]
Im concerned that this may be doo the secrete room that is on the other side. There is a chance the bots are trying to path find to there. Or they just cant comprehend the moving elevator....

**Comment by q3shafe** [comment]
There is a similar issue on area52 where bots kinda get stuck in the upper room with the lift, they can't seem to get off the lift.

**Comment by squiciene** [comment]
i will remake the map & put up a bot clip around the whole area & see if that fixes the problem.
    On Thursday, March 28, 2019, 12:41:09 AM EDT, Shafe Shaffer <notifications@github.com> wrote:  
 
 
There is a similar issue on area52 where bots kinda get stuck in the upper room with the lift, they can't seem to get off the lift.

**Comment by squiciene** [comment]
ok.... i have fixed the issue.   i cant test it as i already have an updated snapshot, & the new files wont override the old ones.  for some reason windows is not letting me attach the file.  i will try to e-mail them to Shafe.

**Comment by q3shafe** [comment]
Updated snapshot is in place and ready to roll

**Comment by angrynerd** [comment]
Cool i will test this out shortly.

**Comment by angrynerd** [comment]
Ok so i done a decent amount of testing on a six bot server with this map and i have not been able to reproduce the issue. This should be tested some more, but im willing to say that its fixed.
