### ISSUE TITLE
legacy map rotations

### ISSUE THREAD

**Issue by angrynerd** [q3shafe/trepidation#204]
Ok so i am having issues with map rotations using the legacy system. mainly this issue occurs when switching rotations. So i have my server start with a rotation of all the original maps that were in the game in the 0.0.20 release. i also have another rotation that has the new maps that have been added in the snapshots. now the first two maps of the main rotation are station144 and hanger19. the first 2 of the new one are station145 and oa_rpg3dm2_s. now when the game starts it will load the first one and i will use rcon or the server console to switch to the new rotation. it will play normal untill the 10 minute round is up and its time to change maps. when it changes it instead of going from station 145 to oa_rpg3dm2_s, will go to hanger19. now this seems to be an issue with vstr nextmap but if i execute that after starting the new rotation it will go to oa_rpg3dm2_s and its only when it happens at the end of a round that it will go to hanger19. for refference my roations and server config is linked below.

i have tested similar styled configs in quake 3 and ef and they both work as expected.
[q3server.txt](https://github.com/q3shafe/trepidation/files/2948839/q3server.txt)

**Comment by angrynerd** [comment]
well my map rotation is a bit more wonky than i had thought which i need to fix but i tested it again and this time it took me to dystopia that is much further down the line. i think it may be using a random map but im almost possitive thats dissabled.

**Comment by q3shafe** [comment]
send all of the rotations your switching between

**Comment by angrynerd** [comment]
this is the first rotatiuon that starts with the server. 
//trep ffa
set tffa "set fraglimit 0; set timelimit 10; set g_gametype 0; seta g_GameMode 0; bot_minplayers 6; set g_instagib 0; vstr p1"
set p1 "map station144; set nextmap vstr p2"
set p2 "map station145; set nextmap vstr p3"
set p3 "map ctf_trepxus; set nextmap vstr p4"
set p4 "map area52; set nextmap vstr p5"
set p5 "map chronic; set nextmap vstr p6"
set p6 "map dangercity; set nextmap vstr p7"
set p7 "map ctf_opposingforts; set nextmap vstr p8"
set p8 "map dread; set nextmap vstr p9"
set p9 "map oa_rpg3dm2; set nextmap vstr p10"
set p10 "map oa_rpg3dm2_s; set nextmap vstr p11"
set p11 "map ctf_junction; set nextmap vstr p12"
set p12 "map outpost; set nextmap vstr p13"
set p13 "map dystopia; set nextmap vstr p14"
set p14 "map dystopia_2; set nextmap vstr p15"
set p15 "map hangar19; set nextmap vstr p16"
set p16 "map ctf_conflictzone; set nextmap vstr p17"
set p17 "map citadel; set nextmap vstr p18"
set p18 "map ctf_aversion; set nextmap vstr p19"
set p19 "map ctf_aversion_2; set nextmap vstr p20"
set p20 "map ctf_battlefield; set nextmap vstr p21"
set p21 "map ctf_battlefield_2; set nextmap vstr p22"
set p22 "map ctf_pyramide; set nextmap vstr p23"
set p23 "map ctf_pyramide2; set nextmap vstr p24"
set p24 "map trep_war_ring; set nextmap vstr p25"
set p25 "map trep_war_ring2; set nextmap vstr p1"

then this is the one is switch to.
//trep new
set new "set fraglimit 0; set timelimit 10; set g_gametype 0; seta g_GameMode 0; bot_minplayers 6; set g_instagib 0; vstr n1"
set n1 "map station145; set nextmap vstr n2"
set n2 "map oa_rpg3dm2_s; set nextmap vstr n3"
set n3 "map dystopia_2; set nextmap vstr n4"
set n4 "map ctf_aversion_2; set nextmap vstr n5"
set n5 "map ctf_battlefield_2; set nextmap vstr n6"
set n6 "map ctf_pyramide2; set nextmap vstr n7"
set n7 "map trep_war_ring2; set nextmap vstr n8"
set n8 "map ctf_junction_2; set nextmap vstr n1"

**Comment by q3shafe** [comment]
Make sure your map rotation is *before* the vstr n1.  Also check g_easymap and g_randommap are set to 0.

**Comment by angrynerd** [comment]
Random map and easy map are off, and n1 has always been before with no
issues.

**Comment by angrynerd** [comment]
This is also a config that is used more than once so it should have saved
the vstrs in the config.

**Comment by angrynerd** [comment]
Yup this one is my bad i still forgot that in .q3a/base trep creates a
separate server file. In that file easy map was turned on so thats fixed
now.
