### ISSUE TITLE
Bots fail to initialize on oa_rpg3dm2_s after last patch

### ISSUE THREAD

**Issue by angrynerd** [q3shafe/trepidation#209]
After the patch that was made in #192 bots nolonger work on this level. this affects both server and single player versions.

**Comment by angrynerd** [comment]
![image](https://user-images.githubusercontent.com/24483958/54169153-e95c0700-4447-11e9-8a6c-a41f9e6a4efb.png)

**Comment by q3shafe** [comment]
That looks like an issue with the aas file, likely just needs recompiled.

**Comment by squiciene** [comment]
heres the new .aas file

[oa_rpg3dm2_s.zip](https://github.com/q3shafe/trepidation/files/2972625/oa_rpg3dm2_s.zip)

**Comment by angrynerd** [comment]
I will test this in a few minutes. If it works i will commit the change.

**Comment by angrynerd** [comment]
ook this fix worked and is to be implemented
