### ISSUE TITLE
Bot Errors

### ISSUE THREAD

**Issue by q3shafe** [q3shafe/trepidation#214]
Any ideas where these are coming from?

Error: BotConstructChat: unknown random string TAUNT_FEM6

Error: BotConstructChat: unknown random string PRAISE3

**Comment by squiciene** [comment]
this sounds like a bot chat problem. this is an issue i will be getting into once all of the texture issues are resolved.

**Comment by angrynerd** [comment]
Most of the textures are good i think the only current problems there is just the monitors on dystopia and junction 2 so...

**Comment by q3shafe** [comment]
huh?

**Comment by q3shafe** [comment]
These look like EF bot chat strings are they in any of your new maps?   

I can probably add them to each of the chatfiles if needed, although it would be easier to just remove them...

**Comment by squiciene** [comment]
chat strings (to the best of my knowledge) are attached to each bot specifically.  if you use a bot with chat problems, the problem will follow the bot into any map it is in.

 i havent messed with bot chat files in a long time.  i am 80% sure they are located in the _c.c file. 
try this;  go into the BOTFILES folder & find the _c.c file for the bot that is malfunctioning.  (example- angrynerdbot_c.c)
 change the .c in to .txt & open it.   you will see the all the bots chatting options & you should see the error.  these files are pretty straight forward & easy to understand.
i could do it, but i cant see if the file i rewrite is working. i have the same problem with maps.  if i make them with the same name as a pre-existing one, then i will only see the  pre-existing & not the one i modified.    
im not sure why this is, but it is.

**Comment by q3shafe** [comment]
I think I can get this fixed... also it isn't a huge deal, just a one off console error.

**Comment by q3shafe** [comment]
fixed
