### ISSUE TITLE
Snapshot build errors

### ISSUE THREAD

**Issue by angrynerd** [q3shafe/trepidation#215]
The snapshot that gets built daily is broken amd not including things. It hasnt included several of the things i have commited. Now when build manually it includes these things and works almost flawlessly but when left to do it automatically it does not work properly. A test file is used to vissualize this from one of my comits. Pewter_merge is present in the manualy buit snapshot but not the automatically built one. This issue needs to be adressed before any major commits happen.

**Comment by q3shafe** [comment]
where is this file again?

**Comment by angrynerd** [comment]
Pak0-gpl2data.pk3/textures/base_floor/pewter_merge

**Comment by q3shafe** [comment]
Fixed
