### ISSUE TITLE
Dread 2 texture errors

### ISSUE THREAD

**Issue by angrynerd** [q3shafe/trepidation#216]
Ok so on last commit i caused a few texture errors in dread with these textures.
![shot0042](https://user-images.githubusercontent.com/24483958/54647153-e5e40380-4a77-11e9-901a-817acfe6eb80.jpg)
![shot0041](https://user-images.githubusercontent.com/24483958/54647154-e5e40380-4a77-11e9-9909-268a7bef041c.jpg)

Now the problem is is i dont know where i went wrong. now this is on a local only build and not in the snaps yet but i had to modify the build script to work with my dorreectories so it may just be my error. at any rate if you could let me know what specific files that the textures are in the picture so that i can track them down and make sure they're were they need to be that would be great.

**Comment by angrynerd** [comment]
![shot0044](https://user-images.githubusercontent.com/24483958/54647752-2c3a6200-4a7a-11e9-8d50-f104a6aca9bd.jpg)
![Uploading shot0045.jpg…these also seem to be messed up so add that to the list...

**Comment by q3shafe** [comment]
Dread 2 looks fine to me now..

**Comment by q3shafe** [comment]
Can someone else test as well with the latest snapshot and confirm it's good and we can close this.

**Comment by squiciene** [comment]
i will later on tonight.

**Comment by squiciene** [comment]
wow, the sky in the 2nd pic looks terrible.

**Comment by angrynerd** [comment]
As i said this may be just the build script i was using. I was trying to fix it at the time... I will test this in a little bit and then we will see.

**Comment by angrynerd** [comment]
so im lowkey retarded and A. thats the wrong junction and B. it was just my build script and the snapshot looks fine.
