### ISSUE TITLE
Aversion 2

### ISSUE THREAD

**Issue by angrynerd** [q3shafe/trepidation#217]
So this isnt a bug but it is something i was concerned about. I did a small scale play test with about 8-10 people on all of the new maps using yesterdays snapshot. Now durring this play through i noticed something on aversion 2. I dont have any acreenshots of this roght now but on the very back of the map if you were to walk off the ledge with aniper rifle on it you would find squiciene's logo. Now the problem with this is its also where the battle shield is. This means that to get the battleshield you have to jump down the bacl there but its not just on the back its hovering over the kill zone. The only way to get it is to grapple bacl up quickly. I mean its not a big issue but i feel like this makes the map gameplay a little off. Im not sure how or if this should be fixed but...

**Comment by squiciene** [comment]
that was meant to be collected by using Flight.  but the grapple approach is quite inventive.   if the players all or mostly agree with you, it can be changed.  just let me know.

**Comment by angrynerd** [comment]
Man i almost feel dumb for not thinking to use flight. Knowing this i will
keep playing and see how that works.
