### ISSUE TITLE
Weds

### ISSUE THREAD

**Issue by q3shafe** [q3shafe/trepidation#218]
Hey All,

I'll be doing a snapshot build tomorrow morning, then on wednesday I'm going to put up a server with that build.

We have a high school gaming club who will be playing weds 3pm-4pm EST,  everyone should try to make it if you can!

Cheers,
Shafe

**Comment by squiciene** [comment]
ok

**Comment by q3shafe** [comment]
Here is the snapshot we'll be playing with.
https://drive.google.com/drive/folders/1YJPkK9JPjMjfKRk65MtiOXKQdXoKmCMO?usp=sharing



@angrynerd I'll get the server config done and tested sometime tues eve...

**Comment by angrynerd** [comment]
Cool i will dl this now and get everything setup on the client side later
today.

**Comment by angrynerd** [comment]
Oh btw please include this with your server.

**Comment by angrynerd** [comment]
it seems the file never actually sent but this is a skin that me and others like to use so if this could be on this server that would be great. thank you!
[md3-bobafett.zip](https://github.com/q3shafe/trepidation/files/3011327/md3-bobafett.zip)

**Comment by q3shafe** [comment]
Kinda defeats the testing process with pure files.. but I'll throw it up there

**Comment by q3shafe** [comment]
Was a great time.. awesome to play with 13-14 players through all of the gametypes/modes!
