### ISSUE TITLE
Radiant

### ISSUE THREAD

**Issue by q3shafe** [q3shafe/trepidation#219]
Hey squiciene have you updated any of the trep-radiant files?

these ones here:
https://github.com/q3shafe/trepidation/tree/master/maptools/radiant

If you have, can you shoot them over so we can have updated map tools?

Cheers!

**Comment by squiciene** [comment]
i updated many files for trep-radiant.  the ones in the link you provided are of no use to me.  it caused way to many development issues, so i had to re-write several files to get it to work right.

im not sure what you mean by "map tools".     i have neither changed tools nor added new ones. the only thing i changed was the working directory.  using the Mapping folder was causing to many problems, so i had to redirect radiant to work out of the base folder.  once i corrected this, all of the development issues went away.   
here are (maybe) all of the files for radiant that i changed.
this one goes in TREP.GAME folder:
[local.zip](https://github.com/q3shafe/trepidation/files/3003955/local.zip)
this one goes in GAMES folder:
[trep.zip](https://github.com/q3shafe/trepidation/files/3003965/trep.zip)
this one goes in GtkRadiant_1.4 folder:
[global.zip](https://github.com/q3shafe/trepidation/files/3003979/global.zip)
 i could swear there was another file or two, but i cant seem to find them.  i could be mistaken about there being more files.  if it wont work right, just let me know & i will dig around a bit more.

**Comment by q3shafe** [comment]
Cool... I was just going to throw them up in so other people could get up and running quickly.  I'll put these up somewhere shortly

**Comment by squiciene** [comment]
do we have a new map builder?

    On Monday, March 25, 2019, 1:10:19 PM EDT, Shafe Shaffer <notifications@github.com> wrote:  
 
 
Cool... I was just going to throw them up in so other people could get up and running quickly. I'll put these up somewhere shortly

**Comment by q3shafe** [comment]
No, but if someone stumbles across trep, it would be awesome if it wasn't a total nightmare to get mapping for it..

Actually one of the kids in the games club expressed an interest, but who knows if that will come around.
