### ISSUE TITLE
needs to be removed from pak1-ccdata

### ISSUE THREAD

**Issue by squiciene** [q3shafe/trepidation#228]
we need to eliminate pyramide2 from pak1-ccdata.  its just the first time i re-made that map & is already replaced with Pyramid_2 which is a better looking version.
efkungfu.shader needs to be removed from pak1-ccdata.  IDK how this file even got to you guys. it has nothing to do with any Trep shaders at all. i guess i sent it by mistake.  efkungfu is a map i built for Voyager.

**Comment by q3shafe** [comment]
I'm confused,  there is ctf_pyaramide2 and ctf_pyramid2 but no Pyramid_2.

I removed the shader file.  but a bit confused about what map is what.

**Comment by squiciene** [comment]
my bad.  you are correct, the map that should stay is ctf_pyramid2.

**Comment by q3shafe** [comment]
Removed and all references to it have been replaced with the proper map
