### ISSUE TITLE
what are these files?

### ISSUE THREAD

**Issue by squiciene** [q3shafe/trepidation#229]
welcome.sfk - battle.ogg.sfk - railgf1a.wav.old & sshot1b.wav.old ?  these are clearly associated with sound files.  what do they do?  i opened them as text files, but i dont understand what im reading there.

**Comment by angrynerd** [comment]
Anything with a .old isnt a text file. Its a sound file that has been
renamed to remove a conflict with a file that is no longer being used there
is a decent chance that most of them can be removed.

**Comment by squiciene** [comment]
thanks for the info.    & sorry i missed game day last week.   i was sick & in bed most of the week & just now remembered.   i would love to see some of the game modes in play by real people.

**Comment by angrynerd** [comment]
This week was spring break but with luck it shouldnt be to hard to setup
again next Wednesday. Generally i do this with that club every Wednesday,
its just not usually on a public server.

**Comment by q3shafe** [comment]
the .sfk files are old sony vegas files used in editing the sounds.  they can go away, the .old files are just old versions of whatever sound they can also likely go away.
