### ISSUE TITLE
original Dread

### ISSUE THREAD

**Issue by squiciene** [q3shafe/trepidation#230]
i just noticed that i never replaced the interior lighting in Dread 1.  i will fix it later on today.   do you guys still want the white  walls removed from blue base?   would you like the red & blue base columns to be more red & blue than the orig?

**Comment by angrynerd** [comment]
Generally the way it is currently looks fine but any fixes or changes are
welcome.

**Comment by q3shafe** [comment]
Did you ever figure out the probs with radiant?  Man, I wish I was more well versed in the level design stuff....

**Comment by squiciene** [comment]
sorry, just got back from orlando.  i havent had time too fix it yet.  im sure i just need to update some file somewhere in Trep to fix it.  i recall there being 2 or more files in trep that direct raidiant. i should have it working within the week.

    On Sunday, April 7, 2019, 10:30:34 PM PDT, Shafe Shaffer <notifications@github.com> wrote:  
 
 
Did you ever figure out the probs with radiant? Man, I wish I was more well versed in the level design stuff....
