### ISSUE TITLE
trep-radiant

### ISSUE THREAD

**Issue by squiciene** [q3shafe/trepidation#231]
after installing the latest snapshot, trep-radiant has stopped working for me.  not sure why this is.  its not even showing the trepidation radiant load screenshot.
i must have deleted a necessary file when i uninstalled trepidation. this may take me a while to fix.
heres a screenshot of the error.
![error](https://user-images.githubusercontent.com/33503125/55653221-db39a600-57bb-11e9-8f9b-7ae77bb7ba11.jpg)

**Comment by q3shafe** [comment]
Oh no... what does the console say about the file it can't find?

**Comment by squiciene** [comment]
the log says it could not find the file - /base/synapse.config.   i found an old copy that worked, but now it tells me the install is broken & im missing the file - /textures/notex.  the log file also shows a variety of other errors. 

i cant seem to find my copy of trep-radiant.  can you post a link for me here?  i need a re-install of it.

**Comment by q3shafe** [comment]
If you download the entire repo here: https://github.com/q3shafe/trepidation/archive/master.zip

You'll find everything in the trepidation/maptools/ folder.

I never ever messed with this so I don't know much about it.

There is also a wiki page about it, but it is just compiled from ancient forum posts: https://planettrepidation.tk/wiki/index.php/Level_Design_/_Mapping_For_Trepidation

**Comment by squiciene** [comment]
ok... i have found the missing files & installed them.  i dont recall ever having those files before, but they are in now.   now i have a new issue.  its not letting me finish running the compile process.   this is gonna take me some more time to figure out.  heres a screen shot of the error, if you have any ideas about it.

![new error](https://user-images.githubusercontent.com/33503125/57037440-375de180-6c25-11e9-8a55-0f742e835e1a.jpg)

**Comment by q3shafe** [comment]
Did this ever get resolved?
